### ISSUE TITLE
Failling to sync repositories

### ISSUE THREAD

**Issue by emanuelserpa** [built-aur/packages#6]
```
erro: falha ao obter o arquivo "built.db" de built.medzik.xyz : The requested URL returned error: 404
erro: falha ao obter o arquivo "built.db" de built-aur.medzik.workers.dev : The requested URL returned error: 404
erro: falha ao obter o arquivo "built.db" de ct8.pl:54267 : The requested URL returned error: 404
erro: falha ao sincronizar todas as bases de dados (erro inesperado)
````
The mirrors are returning 404.

**Comment by name-tar-xz** [comment]
this only happens with x86_64-v3 repos for some reason

**Comment by emanuelserpa** [comment]
Yes, the problem is with x86_64-v3. Hope @MedzikUser have some time to look at this soonish.

**Comment by OskarKarpinski** [comment]
sorry for late

**Comment by OskarKarpinski** [comment]
I noticed this a few days ago, but did a manual database update on the server, but as you can see it didn't change anything, I will investigate the matter in more detail.

**Comment by OskarKarpinski** [comment]
I'll take care of it tomorrow

**Comment by emanuelserpa** [comment]
Cool. Take your time.

**Comment by OskarKarpinski** [comment]
Now the database file is updated.

![image](https://user-images.githubusercontent.com/87065584/200399535-cce76b23-68f6-4426-8e72-7d6bb5aef4e0.png)
